### ISSUE TITLE
Find new name for tool.

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/bigcat#23]
This issue is for brainstorming and collecting ideas for and eventually decide on a new name for BigCAT v2.
These are my current ideas:
 - ATLAS -- **a**dvanced **t**oolkit for **l**abeling **a**nd **s**egmentation
 - (l')art -- (**l**abeling,) **a**nnotation and **r**econstruction **t**ool
 - CART -- **c**ollaborative **a**nnotation and **r**econstruction **t**ool
 - CARE -- **c**ollaborative **a**nnotation and **r**econstruction **e**nvironment

My current favoriate is CARE (*If you want to reconstruct neurons, better use CARE*).

**Comment by jni** [comment]
imho names should be unique strings in Google (or nearly so).

**Comment by bogovicj** [comment]
Must it be an acronym?

Maybe choose an painter/artist and change their name a little:
bondrian (from Mondrian) : <1k hits 
kandinpy (from Kandinsky): 0 hits, but better for a python project 
jothKo (from Rothko): <1k hits

**Comment by jni** [comment]
Anyone know any famous collaborative painting/art projects? =)

**Comment by hanslovsky** [comment]
Very valid remarks @jni @bogovicj 
It does not need to be an acronym but should be meaningful in the context of the tool, either by words (neuro glancer, for example), or by (something close to) an acronym.

**Comment by jni** [comment]
Neurothko? Neurondrian? ;) Neuro-[some famous art collaboration]?

Amusingly, the top hit for "famous art collaboration" is an article by a Nadja *Bozovic*.

**Comment by axtimwalde** [comment]
No neuro please.  I am also split about the painters 

I still like BigArt (BigDataViewer Annotation and Reconstruction Tool).  I also find that BigCat, compared to everything above is not so bad.  Will waste some more time to think about it...

**Comment by bogovicj** [comment]
> Amusingly, the top hit for "famous art collaboration" is an article by a Nadja Bozovic.

:open_mouth: !

**Comment by aschampion** [comment]
BigCat is most memorable and natural to say, but it does imply a scope and relation to CATMAID that may or may not be intended. If it's not intended, it's probably the wrong name.

At least for me, BigArt is awkward on the tongue (almost like "bigot" or "braggart").

Acronyms for big cats are easy (e.g., PUMA - Painting Unconstrained Multiscale Annotations), but fail the unique google test. Acronym misspellings of art-related materials are another possibility. At some point I had debug frontend (for another project) called CAMVAS - Collaborative Annotation for Morphological Visualization, Analysis, and Simulation.

**Comment by axtimwalde** [comment]
BigRat

**Comment by axtimwalde** [comment]
May be we should find some terms that the tool aims to cover and then see what to do with them:

* interactive
* proofreading
* training
* annotation
* collaborative
* segmentation
* big
* data
* reconstruction
* machine learning
* morphology

**Comment by bogovicj** [comment]
This suggests strongly a preference toward an acronym.

[compart](http://www.dictionary.com/browse/compart) - COllaborative morphological proofreading, annotation and reconstruction tool
peridot - proofreading, reconstruction image data tool
tapir - training, annotation, proofreading for image reconstruction
coda - COllaborative data annotation
miastro - morphological, interative annotation ...
diascope  - ...

:man_shrugging: 

These are all real words (or close to), and so fail the google test, but are pronounceable and can be shoehorned into an acronym.

**Comment by axtimwalde** [comment]
Interactive Annotation Reconstruction Proofreading

**Comment by axtimwalde** [comment]
BigCatFX

**Comment by jni** [comment]
BigFXingCat??? 😂

**Comment by funkey** [comment]
Pandera: Pragmatic and Efficient Reconstruction Application.

Phonetically close to [panthera](https://en.wikipedia.org/wiki/Panthera), the genus of biggest cats.

**Comment by axtimwalde** [comment]
P&ERA?  :joy: not bad,  Also close to Pandora who opened that famous box...

**Comment by imagejan** [comment]
> P&ERA

This resolves to PampersandERA for me 😁

**Comment by funkey** [comment]
> Also close to Pandora who opened that famous box...

Ha! The file dialog should then be called "Pandera's box". Makes it much more exciting to click the "open" button.

**Comment by bogovicj** [comment]
I know completely unique names are hard, but does this change the calculus?
http://panderasystems.com/

**Comment by axtimwalde** [comment]
Absolutely, Pandera is out, but there are more vowels in the latin alphabit (;)), e.g. Intelligent, Interactive.

**Comment by aschampion** [comment]
Paintera?

**Comment by hanslovsky** [comment]
@funkey I really like Pandera, just like @axtimwalde I was reminded of Pandora as in the internet radio. That and the link that @bogovicj shared rule out Pandera as a name in my opinion.

Paintera looks like a great way out of this to me @aschampion 
This is my favorite so far.

**Comment by funkey** [comment]
> http://panderasystems.com/

Oh, so sad... My google didn't show that among the first 20 hits or so. Only a mountain in Spain with that name. And what can possibly go wrong with Spanish words, right?

Anyway, Paintera is sweet! :)

**Comment by axtimwalde** [comment]
Paintera is fine, but Pandira is too, just not sure which pronunciations that would trigger...

**Comment by funkey** [comment]
Between the two, I would rather go for Pandira. On a second glance, Paintera

1. …can be misread/pronounced/misheard as pain-ter(r)a (a world of pain!) and
2. …implies that the tool is mainly for painting.

Pandira sounds pretty good to my ears and doesn't associate with anything for me.

**Comment by hanslovsky** [comment]
For (1), you could write it in a way that would prevent that (paintEra, or similar). For (2), it is not only for painting, but it is one of the biggest selling points.

**Comment by funkey** [comment]
1. I personally find this kind of spelling awkward (a capital letter inside the word, or a hyphen). People will get it wrong anyway. Consider as an example all the ways people refer to the multicut (or is it MultiCut, or multi-cut...?). Also, it does not prevent mishearing.
2. Is it? I think the collaborative interaction with a solver will be the unique feature. Ideally, painting should be avoided unless really necessary.

**Comment by aschampion** [comment]
Re (2): an OOM, multiscale, collaborative painting annotation tool is definitely not a filled niche. It will likely have impact on a much larger community than the closed-loop solver interaction; it's just that the latter is much more important to us in connectomics/tracking.

I like that Paintera captures something about the tool without need for an acronym (although one could be made) while incorporating the big cat allusion, but Pandira is also fine. I agree with Jan that weird capitalization is likely to just create stranger pronunciations, but suspect both spellings will have their share of those.

**Comment by funkey** [comment]
Okay then, if no one shares my concerns then they are invalidated, as they were statements about how others would perceive the name :)

So let's see what we have until now:
* paintera*
* pandira*
* BigArt
* BigRat*
* compart
* peridot
* tapir
* coda
* miastro*
* diascope
* Neurothko*
* Neurondrian*
* ATLAS
* (l')art
* CART
* CARE
* bondrian*
* kandinpy*
* jothKo*

marked with * are (almost) unique names.

Other suggestions?

**Comment by hanslovsky** [comment]
Thanks @funkey for summarizing these names. Based on the previous discussion, I think we should drop the names that show a severe lack of uniqueness (c&p'ed from @funkey 's post):
* paintera*
* pandira*
* BigRat*
* miastro*
* Neurothko*
* Neurondrian*
* bondrian*
* kandinpy*
* jothKo*

paintera could also be spelled painthera

**Comment by funkey** [comment]
Painthera! It even comes with a slogan and a mascot! ;)

![painthera](https://user-images.githubusercontent.com/776708/34216545-ecac8afa-e5a8-11e7-877e-ac0de588f720.jpg)

**Comment by hanslovsky** [comment]
Haha, perfect. So painthera is out as well.

**Comment by tinevez** [comment]
BigOVIC
---------

The Big Omni View Interactive and Collaborativeannotationtool.

**Comment by hanslovsky** [comment]
As the auto mesh-generation and multi-scale painting come closer to a state where we can merge the progress of BigCAT v2 into master, we should also decide on the name. I suggest we go with *paintera*:
 - Captures an important aspect without acronym
 - alludes to BigCat in a very nice way
 - Cool logos possible (e.g. a big cat with a brush in its mouth or a brush for its tail)

**Comment by axtimwalde** [comment]
I prefer pandira, @funkey already owns the domain, it does not allude to pain therapy, and it may allow for panda based logos.

**Comment by hanslovsky** [comment]
I own the paintera domain now, so that levels the field with respect to the domain.
Google image search for pandira shows a lot of Jesus pictures, as Yeshu ben Pandera/Pandira seems to be a potential candidate for the historical Jesus.

**Comment by hanslovsky** [comment]
[saalfeldlab/paintera](https://github.com/saalfeldlab/paintera) it is!
