### ISSUE TITLE
Alt+S often does not work for a viewer instance

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/bigcat#60]
This holds true for the entire lifetime of the viewer and is random.

**Comment by axtimwalde** [comment]
Alt+moving the window seems to fix this sometimes.  I am on Ubuntu 16.04Unity, so this may be an undesired interaction with Gnome/ Unity.  Will keep watching it...

**Comment by hanslovsky** [comment]
Does that mean we should avoid using `Alt` as a modifier key in general? Ubuntu is probably going to be most commonly used amonst BigCAT users.

**Comment by axtimwalde** [comment]
Yes.  I added plain "P" as an alternative key and that always works.  The Alt issue may also be realated to VNC forwarding, but I would  like to avoid unnecessary glitches.

**Comment by hanslovsky** [comment]
Can you check if it happens with regular use (not through VNC)?

**Comment by axtimwalde** [comment]
Yes it happened once.  I suggest, we avoid the Alt modifier where not necessary, just like the Windows key, Ctrl and Shift are already more than what one would like to have.

**Comment by hanslovsky** [comment]
I can live with that. `P` like "preferences" makes sense as well (the functionality of that sidebar is now extended well beyond just showing a list of sources).

**Comment by hanslovsky** [comment]
I found only one occurence of `KeyCode.ALT`. I will remove it and close this issue.
