### ISSUE TITLE
BDV keyboard controls for navigation incomplete

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/bigcat#64]
I am particularly missing
* Cursor Up and Cursor Down for zoom in and out (currently they lead to unexpected mode changes)
* "," and "." (<,>) to advance and retract through sections
* "I" to switch interpolation of the currently active source

**Comment by hanslovsky** [comment]
The last bullet point will be a little more involved as right now, there is only a global interpolation setting. For now, I will just change this global interpolation.

**Comment by hanslovsky** [comment]
The merge of #66 closes this. Adding per source interpolation as specified in the last bullet point is more involved and will be addressed in #67 and #68
