### ISSUE TITLE
Make Label.BACKGROUND transparent in viewer

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/bigcat#75]
Currently we assign a color with non-zero alpha. This should not be the case. When fixing this, also  ensure that the other remaining special purpose ids defined in the `Label` class are treated properly. For some of them it may make sense to assign and expose color as a parameter.

**Comment by axtimwalde** [comment]
Instead of Label.BACKGROUND, Label.TRANSPARENT should be transparent.

**Comment by hanslovsky** [comment]
The correct label is set to transparent in 575db6c0f48d073d5af45b519ea7de2d2c3d3b68
