### ISSUE TITLE
DataSource.createN5MipmapSource uses wrong offset

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/bigcat#86]
https://github.com/saalfeldlab/bigcat/blob/javafx-generic-listeners/src/main/java/bdv/bigcat/viewer/atlas/data/DataSource.java#L337-L340

**Comment by axtimwalde** [comment]
True, should be resolution * downsampleFactor, correct?

**Comment by hanslovsky** [comment]
I am not 100% sure because I determine the source transform a little differently:
https://github.com/saalfeldlab/bigcat/blob/javafx-generic-listeners/src/main/java/bdv/bigcat/viewer/atlas/opendialog/BackendDialogN5.java#L133-L160
 1. determine the appropriate scale factors and use the world coordinate offset as offset (A)
 2. determine the translation to move downscaled source into origin of highest resolution source (t)
 3. `A.concatenate( t )`
I did some math on paper and I think it is correct. Before we fix this, I will re-do the math and upload it somewhere (latex/html) for reference.

**Comment by hanslovsky** [comment]
Continued in saalfeldlab/paintera#10
